export const tab_page_wrapper: string;
export const scaffold_wrapper: string;
export const left_panel: string;
export const right_panel: string;
export const one_role: string;
export const role_name: string;
export const add_new_role_button: string;
export const add_new_role_section: string;
export const add_new_role_buttons_wrapper: string;