apiVersion: v1
kind: Pod
metadata:
  name: ukb-curator-pod
  labels:
    app: itmat-ukb-curator
namespace: itmat-broker
spec:
  containers:
  - name: itmat-ukb-curator-container
    image: chonsou/itmat-ukb-curator
    resources:
      requests:
        memory: "2Gi"
    ports:
      - containerPort: 8080
    readinessProbe:
      httpGet:
        path: /readinesscheck
        port: 3401
      initialDelaySeconds: 5
      timeoutSeconds: 1
      periodSeconds: 15
    livenessProbe:
      httpGet:
        path: /livenesscheck
        port: 3401
      initialDelaySeconds: 90
      timeoutSeconds: 1
      periodSeconds: 15