export const tab_page_wrapper: string;
export const one_role: string;
export const role_name: string;
export const add_new_role_button: string;
export const add_new_role_section: string;
export const add_new_role_buttons_wrapper: string;
export const role_header: string;
export const delete_role_button: string;
export const right_aligned: string;