import * as appUsers from './appUsers';
import * as organisation from './organisation';
import * as pubkey from './pubkey';
import * as curation from './curation';
import * as fields from './fields';
import * as files from './files';
import * as log from './log';
import * as permission from './permission';
import * as projects from './projects';
import * as query from './query';
import * as study from './study';
import * as user from './user';
import * as subscription from './subscription';
import * as standardization from './standardization';
export * from './appUsers';
export * from './organisation';
export * from './pubkey';
export * from './curation';
export * from './fields';
export * from './files';
export * from './log';
export * from './permission';
export * from './projects';
export * from './query';
export * from './study';
export * from './user';
export * from './subscription';
export * from './standardization';
export const GQLRequests = { ...subscription, ...appUsers, ...organisation, ...pubkey, ...curation, ...fields, ...files, ...log, ...permission, ...projects, ...query, ...study, ...user, ...standardization };
