export enum errorCodes {
    DATABASE_ERROR = 'DATABASE_ERROR',
    NOT_LOGGED_IN = 'NOT_LOGGED_IN',
    CLIENT_MALFORMED_INPUT = 'CLIENT_MALFORMED_INPUT',
    CLIENT_ACTION_ON_NON_EXISTENT_ENTRY = 'CLIENT_ACTION_ON_NON_EXISTENT_ENTRY',
    AUTHENTICATION_ERROR = 'AUTHENTICATION_ERROR',
    NO_PERMISSION_ERROR = 'NO_PERMISSION_ERROR',
    FILE_STREAM_ERROR = 'FILE_STREAM_ERROR',
    OBJ_STORE_ERROR = 'OBJ_STORE_ERROR',
    UNQUALIFIED_ERROR = 'UNQUALIFIED_ERROR'
}
