export enum fileTypes {
    STUDY_REPO_OBJ_STORE_FILE = 'STUDY_REPO_OBJ_STORE_FILE',
    STUDY_REPO_SCRIPT_FILE = 'STUDY_REPO_SCRIPT_FILE',
    STUDY_REPO_DIR = 'STUDY_REPO_DIR',
    USER_PERSONAL_FILE = 'USER_PERSONAL_FILE ',
    USER_PERSONAL_DIR = 'USER_PERSONAL_DIR'
}