export const deviceTypes: Record<string, string> = {
    AX6: 'Axivity',
    BVN: 'Biovotion',
    BTF: 'Byteflies',
    MMM: 'McRoberts',
    DRM: 'Dreem',
    VTP: 'VitalPatch',
    BED: 'VTT Bed Sensor',
    YSM: 'ZKOne',
    MBT: 'Mbient',
    IDE: 'German Interview Transcripts',
    IEN: 'English Interview Transcripts',
    INL: 'Dutch Interview Transcripts',
    TEQ: 'Technology Experience Questionnaire',
    PSG: 'PSG Study Polysomnography Data',
    PSR: 'PSG raw data',
    PSM: 'PSG meta data',
    SMA: 'Stress Monitor App',
    TFA: 'ThinkFast App',
    SMQ: 'Stress Monitor App Questionnaire',
    VIR: 'Virtual device type',
    CAN: 'Cantab App',
    TUP: 'Cantab TUP data',
    WLD: 'Wildkey App',
    SOC: 'Wildkey Social App',
    SLP: 'Derived BED Sleep Features',
    STS: 'Derived AX6 Kinematic Features',
    CCL: 'Derived CAN Cognitive Performance Metrics',
    WKT: 'Derived WLD Typing Features',
    WKS: 'Derived SOC Social Features',
    HRV: 'Derived VTP HRV Features',
    VIT: 'Derived VTP Basic Features',
    GVA: 'Derived AX6 Gait Features'
};
