[package]
name = "acacia-clinical-data-service"
version = "0.1.0"
authors = ["sou-chon <sou.chon@outlook.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
kafka = "0.8"
mongodb = "2.0.0-alpha"
tokio = { version = "1", features = ["full"] }
serde = "1.0.124"
uuid = "0.8.2"
